### ISSUE TITLE
Export to vrscene error (since 20180508)

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#239]
Since 20180508, I'm seeing this error reported during F12 render to V-ray from blender for moderately complex scenes (:

[2018/Aug/28|22:24:11] Reading scene file "C:\Users\phils\AppData\Local\Temp\vrayblender_standalone\scene_scene.vrscene"
[2018/Aug/28|22:24:11] error: Error in file "C:\Users\phils\AppData\Local\Temp\vrayblender_standalone\scene_nodes.vrscene", line 198190: Token ")" not recognized as valid token

The immediately prior build is fine. From the nightlies repository :

good : fe0cca4
bad : 05b23c4

There seem to be quite a few commits between these builds, and the error output is not very helpful to pin this down further.

**Comment by bdancer** [comment]
It's not related to the scene complexity, just some plugin data is written incorrectly. I'll need a scene to check which object causes this.

**Comment by philstopford** [comment]
I'm attempting to get a scene of reasonable size for you. Essentially, what I am seeing is that the error comes up for a linked scene, where that linked scene has geometry being driven by an alembic file.

I've been trying to reduce my large scene down to get something less heavy but perhaps this helps in the meantime.

**Comment by philstopford** [comment]
OK. So this should break. The alembic file doesn't seem to be necessary to trigger the error and the images are also left out, for size concerns. I hope this is helpful enough.

To trigger this, unpack the attached. 'crowd1' is used by 'debug.blend'. To see the problem, link the sidewalk_groups 'group' from debug.blend file into an empty scene. Hit F12 to render and you should get the error reported.

If you simply open debug.blend and hit F12, V-ray will render without error.

[vray_link_bug.zip](https://github.com/ChaosGroup/blender_with_vray_additions/files/2332230/vray_link_bug.zip)

**Comment by poseidon4o** [comment]
@philstopford I pushed a fix that will not export invalid scene. Please check tomorrow's nightly (20180830) if the export is correct.

**Comment by philstopford** [comment]
Looks good - thanks very much for the rapid fix.
