### ISSUE TITLE
Drivers in shading tree (Python node trees)

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#240]
V-ray for blender nodes offer the potential to use drivers, but they aren't showing up in the graph editor for configuration. I'm not certain whether this is supposed to work (it would be great if they could, to enable rigged surface using empties to drive blending of images, etc. for an entire surface).

I started a forum thread here (https://forums.chaosgroup.com/forum/v-ray-for-blender-forums/v-ray-for-blender-tips-tricks-and-tutorials/1008491-using-drivers-in-v-ray-shading-networks), but wanted to also file a ticket for tracking purposes.

**Comment by philstopford** [comment]
Here's a simple example using Cycles, with an empty driving a blend between the red and green images as it moves in Y over 10 frames. I can't reproduce this in V-ray, to affect both objects across their entire surface.

[driver_demo_compact.zip](https://github.com/ChaosGroup/blender_with_vray_additions/files/2333396/driver_demo_compact.zip)

**Comment by bdancer** [comment]
Cycles is using completely different shading networks (written in C), while V-Ray uses Python node trees and those trees unfortunately do not support drivers.

**Comment by philstopford** [comment]
That's a shame. Has there been contact with the blender developers to see whether they could add the support you need?

**Comment by bdancer** [comment]
I'll check what could be done about that...

**Comment by philstopford** [comment]
I wanted to follow up in case there was news or more that I could do to help. This is one of my main pain-points right now.

**Comment by bdancer** [comment]
You could report that drivers do not work with Python nodes. I can't do much about this issue.

**Comment by philstopford** [comment]
A thread on devtalk.blender.org brought up this : https://github.com/LuxCoreRender/BlendLuxCore/issues/167

Would that approach help?

**Comment by bdancer** [comment]
> Would that approach help?

Not much.

**Comment by philstopford** [comment]
With build ddba5f3 I see the input value on Float updating, but the luminosity or color blend does not respond. It looks like there was a later commit that might be related, but I wanted to ask. Updated blend file with the V-ray setup is attached, in case useful.
[driver_demo_compact.zip](https://github.com/ChaosGroup/blender_with_vray_additions/files/2377251/driver_demo_compact.zip)

**Comment by bdancer** [comment]
You mean self-illumination doesn't work?
This is another issue. TexFloat output has incorrect type and it's a bug. It should have "grey" float socket output.
Use "Float To Color" texture instead.

**Comment by philstopford** [comment]
It doesn't look like the blend sees the output of the float (even routed through color to float) : 
![capture](https://user-images.githubusercontent.com/1983851/45484746-37a37e00-b723-11e8-9c71-606dc5aa5cc4.PNG)
[driver_demo_compact.zip](https://github.com/ChaosGroup/blender_with_vray_additions/files/2378987/driver_demo_compact.zip)

**Comment by bdancer** [comment]
Ok, this is also not related to drivers. This is some export bug.
As a workaround use driver directly in "Blend Amount".

**Comment by philstopford** [comment]
Using the workaround makes things OK. Do you need a separate ticket for the 'export bug' as you describe it?
