### ISSUE TITLE
Can't build the current source (VS2017)

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#241]
I am not certain whether the build instructions are up to date. I was hoping to get a local build set up here. I can easily build regular blender with my development environment, but the V-ray version seems to fail with many linker errors (unresolved symbols), across OpenColorIO, OSL, 

I followed the instructions to clone the repository and ensured I have the external libraries (zmq, libsodium) in-place and this doesn't look related. I'm building against the blender.org libs package for vc14 x64, which would seem to be valid.

Over 118 linker errors are reported when I try to build the current source.

Is VS2017 supported?

**Comment by philstopford** [comment]
No - VS2017 is supported : https://wiki.blender.org/wiki/Building_Blender/Windows#Visual_Studio

**Comment by bdancer** [comment]
Ok, then what are the errors?

**Comment by philstopford** [comment]
[build.log](https://github.com/ChaosGroup/blender_with_vray_additions/files/2339933/build.log)

**Comment by philstopford** [comment]
Massaging the master, I now only have these errors in the build with VS 2017:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl OSL_v1_9::OSLQuery::nparams(void)const " (__imp_?nparams@OSLQuery@OSL_v1_9@@QEBA_KXZ) referenced in function "struct _object * __cdecl vfb_osl_update_node_func(struct _object *,struct _object *)" (?vfb_osl_update_node_func@@YAPEAU_object@@PEAU1@0@Z)	blender	D:\development\blender-git\b_v\source\creator\vray_for_blender_rt.lib(vfb_python_api.obj)	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl OSL_v1_9::OSLQuery::nparams(void)const " (__imp_?nparams@OSLQuery@OSL_v1_9@@QEBA_KXZ)	blender	D:\development\blender-git\b_v\source\creator\vray_for_blender_rt.lib(vfb_export_shader.obj)	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: struct OSL_v1_9::OSLQuery::Parameter const * __cdecl OSL_v1_9::OSLQuery::getparam(unsigned __int64)const " (__imp_?getparam@OSLQuery@OSL_v1_9@@QEBAPEBUParameter@12@_K@Z) referenced in function "struct _object * __cdecl vfb_osl_update_node_func(struct _object *,struct _object *)" (?vfb_osl_update_node_func@@YAPEAU_object@@PEAU1@0@Z)	blender	D:\development\blender-git\b_v\source\creator\vray_for_blender_rt.lib(vfb_python_api.obj)	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: struct OSL_v1_9::OSLQuery::Parameter const * __cdecl OSL_v1_9::OSLQuery::getparam(unsigned __int64)const " (__imp_?getparam@OSLQuery@OSL_v1_9@@QEBAPEBUParameter@12@_K@Z)	blender	D:\development\blender-git\b_v\source\creator\vray_for_blender_rt.lib(vfb_export_shader.obj)	1	
Error	LNK1120	2 unresolved externals	blender	D:\development\blender-git\b_v\bin\Release\blender.exe	1

**Comment by philstopford** [comment]
I noticed that you merged master recently; did that help with the VS2017 compile side of things? It looks like I'm still bumping against libsodium/libzeromq linking issues that I'm not sure how to resolve.

**Comment by poseidon4o** [comment]
@philstopford Hey it looks like OSL is failing to link, all the OSL libs we depend on are the ones provided in the svn repo: https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14 - make sure to update it.

Alternatively you could disable *all* OSL with WITH_CYCLES_OSL=OFF, to test if it will build.

We recently switched to VS2017 as compiler for nightly builds. It is strange that you get unresolved externals only in vray_for_blender_rt.lib, could you post the cmake configure line you use.

**Comment by philstopford** [comment]
[CMakeCache.txt](https://github.com/ChaosGroup/blender_with_vray_additions/files/2450725/CMakeCache.txt)

Attempt to build this morning after 'make update' inside the blender-for-vray folder

 yields:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl OSL_v1_9::OSLQuery::nparams(void)const " (__imp_?nparams@OSLQuery@OSL_v1_9@@QEBA_KXZ) referenced in function "struct _object * __cdecl vfb_osl_update_node_func(struct _object *,struct _object *)" (?vfb_osl_update_node_func@@YAPEAU_object@@PEAU1@0@Z)	blender	D:\development\blender-git\bv\source\creator\vray_for_blender_rt.lib(vfb_python_api.obj)	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl OSL_v1_9::OSLQuery::nparams(void)const " (__imp_?nparams@OSLQuery@OSL_v1_9@@QEBA_KXZ)	blender	D:\development\blender-git\bv\source\creator\vray_for_blender_rt.lib(vfb_export_shader.obj)	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: struct OSL_v1_9::OSLQuery::Parameter const * __cdecl OSL_v1_9::OSLQuery::getparam(unsigned __int64)const " (__imp_?getparam@OSLQuery@OSL_v1_9@@QEBAPEBUParameter@12@_K@Z) referenced in function "struct _object * __cdecl vfb_osl_update_node_func(struct _object *,struct _object *)" (?vfb_osl_update_node_func@@YAPEAU_object@@PEAU1@0@Z)	blender	D:\development\blender-git\bv\source\creator\vray_for_blender_rt.lib(vfb_python_api.obj)	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: struct OSL_v1_9::OSLQuery::Parameter const * __cdecl OSL_v1_9::OSLQuery::getparam(unsigned __int64)const " (__imp_?getparam@OSLQuery@OSL_v1_9@@QEBAPEBUParameter@12@_K@Z)	blender	D:\development\blender-git\bv\source\creator\vray_for_blender_rt.lib(vfb_export_shader.obj)	1	
Error	LNK2019	unresolved external symbol randombytes_close referenced in function "public: __cdecl zmq::ctx_t::~ctx_t(void)" (??1ctx_t@zmq@@QEAA@XZ)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(ctx.obj)	1	
Error	LNK2019	unresolved external symbol crypto_box_keypair referenced in function zmq_curve_keypair	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(zmq_utils.obj)	1	
Error	LNK2001	unresolved external symbol crypto_box_keypair	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_client.obj)	1	
Error	LNK2001	unresolved external symbol crypto_box_keypair	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol sodium_init referenced in function "public: __cdecl zmq::curve_client_t::curve_client_t(struct zmq::options_t const &)" (??0curve_client_t@zmq@@QEAA@AEBUoptions_t@1@@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_client.obj)	1	
Error	LNK2001	unresolved external symbol sodium_init	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol crypto_box_beforenm referenced in function "private: int __cdecl zmq::curve_client_t::process_welcome(unsigned char const *,unsigned __int64)" (?process_welcome@curve_client_t@zmq@@AEAAHPEBE_K@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_client.obj)	1	
Error	LNK2001	unresolved external symbol crypto_box_beforenm	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol crypto_box referenced in function "private: int __cdecl zmq::curve_client_t::produce_hello(class zmq::msg_t *)" (?produce_hello@curve_client_t@zmq@@AEAAHPEAVmsg_t@2@@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_client.obj)	1	
Error	LNK2001	unresolved external symbol crypto_box	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol crypto_box_open referenced in function "private: int __cdecl zmq::curve_client_t::process_welcome(unsigned char const *,unsigned __int64)" (?process_welcome@curve_client_t@zmq@@AEAAHPEBE_K@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_client.obj)	1	
Error	LNK2001	unresolved external symbol crypto_box_open	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol crypto_box_afternm referenced in function "public: virtual int __cdecl zmq::curve_client_t::encode(class zmq::msg_t *)" (?encode@curve_client_t@zmq@@UEAAHPEAVmsg_t@2@@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_client.obj)	1	
Error	LNK2001	unresolved external symbol crypto_box_afternm	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol crypto_box_open_afternm referenced in function "public: virtual int __cdecl zmq::curve_client_t::decode(class zmq::msg_t *)" (?decode@curve_client_t@zmq@@UEAAHPEAVmsg_t@2@@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_client.obj)	1	
Error	LNK2001	unresolved external symbol crypto_box_open_afternm	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol randombytes referenced in function "private: int __cdecl zmq::curve_client_t::produce_initiate(class zmq::msg_t *)" (?produce_initiate@curve_client_t@zmq@@AEAAHPEAVmsg_t@2@@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_client.obj)	1	
Error	LNK2001	unresolved external symbol randombytes	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol crypto_secretbox referenced in function "private: int __cdecl zmq::curve_server_t::produce_welcome(class zmq::msg_t *)" (?produce_welcome@curve_server_t@zmq@@AEAAHPEAVmsg_t@2@@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK2019	unresolved external symbol crypto_secretbox_open referenced in function "private: int __cdecl zmq::curve_server_t::process_initiate(class zmq::msg_t *)" (?process_initiate@curve_server_t@zmq@@AEAAHPEAVmsg_t@2@@Z)	blender	D:\development\blender-git\bv\source\creator\libzmq.lib(curve_server.obj)	1	
Error	LNK1120	13 unresolved externals	blender	D:\development\blender-git\bv\bin\Release\blender.exe	1	
Error	MSB3073	The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	138

**Comment by poseidon4o** [comment]
Just pushed a repo with pre-built libs we use in nightlies: https://github.com/ChaosGroup/vray_for_blender_libs try with these.

**Comment by philstopford** [comment]
Your libraries worked. From inspection, I have a sodium directory in libs/Windows where your archive does not (it seemed to be needed based on https://github.com/ChaosGroup/blender_with_vray_additions, but your package suggests otherwise, at least for Windows).

The file sizes are also slightly different for the libzmq static binary - I used 4.1.4 of libzeromq and 1.0.16 of the sodium library, in case that matters.

**Comment by poseidon4o** [comment]
ZMQ is built without sodium on windows as it is not strict requirement. The linux and macos are not yet updated with that so they include libsodium.

**Comment by philstopford** [comment]
Whilst the build works, the resulting binary doesn't seem to have the V-ray addon available. I'm looking into why that might be.

**Comment by poseidon4o** [comment]
How do you determine that? On first run you need to enable the addon: File -> User Preferences -> Addons  -> Render -> Render: V-Ray For Blender 3.0

https://i.imgur.com/49vuxVp.png

**Comment by poseidon4o** [comment]
Did you clone the python exporter (vb30 module)? Last two steps from here: https://github.com/ChaosGroup/blender_with_vray_additions/blob/dev/vray_for_blender/vb35/README.md

**Comment by philstopford** [comment]
Indeed - I missed that bit. I cleaned up everything to try again. I'll give that a go and see whether the addon appears. I'll then re-enable OSL and see if that also continues to build cleanly. Thanks for the assistance so far - much appreciated.

**Comment by philstopford** [comment]
Having the OSL enabled seems to prevent the build from working with your libraries :

142>   Creating library D:/development/blender-git/bv/bin/Release/blender.lib and object D:/development/blender-git/bv/bin/Release/blender.exp
142>vray_for_blender_rt.lib(vfb_python_api.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl OSL_v1_9::OSLQuery::nparams(void)const " (__imp_?nparams@OSLQuery@OSL_v1_9@@QEBA_KXZ) referenced in function "struct _object * __cdecl vfb_osl_update_node_func(struct _object *,struct _object *)" (?vfb_osl_update_node_func@@YAPEAU_object@@PEAU1@0@Z)
142>vray_for_blender_rt.lib(vfb_export_shader.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl OSL_v1_9::OSLQuery::nparams(void)const " (__imp_?nparams@OSLQuery@OSL_v1_9@@QEBA_KXZ)
142>vray_for_blender_rt.lib(vfb_python_api.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct OSL_v1_9::OSLQuery::Parameter const * __cdecl OSL_v1_9::OSLQuery::getparam(unsigned __int64)const " (__imp_?getparam@OSLQuery@OSL_v1_9@@QEBAPEBUParameter@12@_K@Z) referenced in function "struct _object * __cdecl vfb_osl_update_node_func(struct _object *,struct _object *)" (?vfb_osl_update_node_func@@YAPEAU_object@@PEAU1@0@Z)
142>vray_for_blender_rt.lib(vfb_export_shader.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: struct OSL_v1_9::OSLQuery::Parameter const * __cdecl OSL_v1_9::OSLQuery::getparam(unsigned __int64)const " (__imp_?getparam@OSLQuery@OSL_v1_9@@QEBAPEBUParameter@12@_K@Z)
142>D:\development\blender-git\bv\bin\Release\blender.exe : fatal error LNK1120: 2 unresolved externals


[osl_build_log.txt](https://github.com/ChaosGroup/blender_with_vray_additions/files/2451175/osl_build_log.txt)

**Comment by philstopford** [comment]
With OSL disabled, the build completes and running the git clone sequence to get the exporter allows it to show up in blender when launched, so that's progress. Not sure why OSL should cause such trouble, though.

**Comment by poseidon4o** [comment]
What revision is your svn repository with prebuilt libs (win64_vc14)? Mine is at 62143.
Also what is the commit you are building from for Blender itself?

**Comment by philstopford** [comment]
I updated when I first started this morning; the libs revision is below. It looks like a couple of commits were made to the V-ray blender code this morning, so I didn't have those locally. Not sure if you expect a difference but I'll try the build with the output of the below:

D:\development\blender-git\blender-for-vray>make update
Updating 'D:\development\blender-git\lib\win64_vc14':
At revision 62143.
Unpacking objects: 100% (13/13), done.Unpacking objects:   7% (1/13)

remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 13 (delta 10), reused 12 (delta 9), pack-reused 0
From https://github.com/bdancer/blender-for-vray
   527770e47a..89f1c0ac73  dev/vray_for_blender/vb35 -> origin/dev/vray_for_blender/vb35
 * [new branch]            dev/lyubomir.koev/msvc2017 -> origin/dev/lyubomir.koev/msvc2017
Updating 527770e47a..89f1c0ac73
Fast-forward
 CMakeLists.txt                 | 29 ++++++++++++++++++++---------
 README.md                      | 28 +++++++++++++++-------------
 build_files/cmake/macros.cmake | 21 +++++++--------------
 3 files changed, 42 insertions(+), 36 deletions(-)
Current branch dev/vray_for_blender/vb35 is up to date.
Entering 'intern/vray_for_blender_rt/extern/vray-zmq-wrapper'
From https://github.com/ChaosGroup/vray_for_blender_zmq_wrapper
 * branch            master     -> FETCH_HEAD
Already up to date.
HEAD is up to date.
Entering 'release/datafiles/locale'
From git://git.blender.org/blender-translations
 * branch            master     -> FETCH_HEAD
Already up to date.
HEAD is up to date.
Entering 'release/scripts/addons'
From git://git.blender.org/blender-addons
 * branch              master     -> FETCH_HEAD
Already up to date.
HEAD is up to date.
Entering 'release/scripts/addons_contrib'
From git://git.blender.org/blender-addons-contrib
 * branch            master     -> FETCH_HEAD
Already up to date.
HEAD is up to date.
Entering 'source/tools'
From git://git.blender.org/blender-dev-tools
 * branch            master     -> FETCH_HEAD
Already up to date.
HEAD is up to date.

**Comment by philstopford** [comment]
Same issue when OSL is enabled with the current code noted above.

**Comment by poseidon4o** [comment]
Actually I added this to the configuration, please update the source and try to build

**Comment by philstopford** [comment]
That seems to make the system happy. OSL shows up.

This looks good now.

Is it expected (I also see it in the official nightly builds) that the general settings compute device appears different to the regular blender builds (i.e. the GTX 1060 isn't shown)? How is CUDA handled in the V-ray builds vs the vanilla blender code?

**Comment by philstopford** [comment]
CUDA working nicely. I think that covers everything.

If there was a desire to merge blender master with the current V-ray/blender code, how is that typically done - I see numerous mentions of merging blender master with this project, but the technique escapes me.

**Comment by poseidon4o** [comment]
If you want to merge the latest changes from master you need to add the blender repo as remote, get the changes from the upstream master and merge them to the dev/vray_for_blender/vb35 branch (or any branch you use for development):
```git remote add upstream git://git.blender.org/blender.git```
```git checkout master```
```git pull upstream master```
```git checkout dev/vray_for_blender/vb35```
```git merge master```

**Comment by philstopford** [comment]
I think this, from my perspective, can be closed now. The original issue is resolved: I can happily build with VS2017 and the resulting binary works just fine.

**Comment by poseidon4o** [comment]
Last change was by mistake I will close it now
