### ISSUE TITLE
VFB appears on-top of all other windows

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#242]
The VFB seems to display on-top of all other windows, which makes it tricky to work as a render is cooking. Could this be revised, or is there already an option somewhere to change this behavior?

**Comment by bdancer** [comment]
You could edit vb30/lib/VRayProcess.py and change VRAY_VFB_ALWAYS_ON_TOP value to 0.

**Comment by philstopford** [comment]
Could it be made an option from the UI that would survive reinstalls and also propagate through blender cloud settings sync?

**Comment by bdancer** [comment]
Yes, it's possible.

**Comment by bdancer** [comment]
Done: https://github.com/ChaosGroup/vray_for_blender_exporter/commit/221fbfec957fed2759ef69b4cbde2fce669fb74a

**Comment by philstopford** [comment]
Is there a global preference for this? I see the scene preference, but there's no 'on top' preference in the add-on settings (where you can specify the VRAY_PATH), to make a global setting.

**Comment by bdancer** [comment]
There is no global preference for this.
