### ISSUE TITLE
Large tiled EXR yields a crash

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#244]
Blender itself has issues with large images due to the apparent need to create a GL preview. For V-ray, I hoped this might be different and I could use a large tiled EXR without trouble as the GL view shouldn't be a factor. Doing so, though, I get a crash : 

ui_template_id: pointer property not found: Object.active_texture

C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\startup\bl_ui\space_node.py:99
ui_template_id: pointer property not found: Object.active_texture

C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\startup\bl_ui\space_node.py:99
ui_template_id: pointer property not found: Object.active_texture

C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\startup\bl_ui\space_node.py:99
ui_template_id: pointer property not found: Object.active_texture

C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\startup\bl_ui\space_node.py:99
Calloc returns null: len=2655518720 in imb_addrectfloatImBuf, total 26401488
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF646D243FA
Module  : C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\blender.exe

The tiled EXR seems to be valid and worked without issue in V-ray/MODO.

The tiled EXR in question is rather large (some 12 GB on-disk), but could be uploaded if useful, given an appropriate destination to upload it to.

**Comment by bdancer** [comment]
This looks like an unreleated crash.
All textures used in V-Ray shading trees are just text fields and the file itself gets loaded only at render time.

> ui_template_id: pointer property not found: Object.active_texture

Such messages could appear sometimes when switching render engines.

But still will be good to investigate the exact reason of the crash. Could you upload the scene (without exr)?

**Comment by philstopford** [comment]
Haven't forgotten about this. There's not really anything about the blend file. The crash happens when loading the image. For example, add a basic sphere. Add a material and then, in the V-ray node graph, add an image texture. Browse for the large EXR file and blender will fail:

Calloc returns null: len=2655518720 in imb_addrectfloatImBuf, total 27083864
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7EAC05AFA
Module  : C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\blender.exe

**Comment by bdancer** [comment]
Will crash happen if you'll use this texture in some native Blender node?

**Comment by philstopford** [comment]
It happens there because the viewport tries to evaluate it for OpenGL, and this yields a crash. For V-ray, I was hoping this wasn't the case. If blender in any case evaluates the image for display, does V-ray have an option to have a viewport-only texture as a stand-in for a high resolution image that the renderer will use?

**Comment by bdancer** [comment]
So, it'a Blender issue and I'm not sure how I can help.

> does V-ray have an option to have a viewport-only texture as a stand-in for a high resolution image that the renderer will use?

No, it does not.

**Comment by philstopford** [comment]
Blender always evaluates a texture in a node for OpenGL display?

**Comment by bdancer** [comment]
@philstopford I've really no idea what Blender is doing...
