### ISSUE TITLE
Crash on F12: access violation

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#245]
Hello,

I have a scene that was previously rendering OK with V-ray / Blender (and renders fine with Cycles). Today, it seems to be having trouble : 

V-Ray For Blender: V-Ray For Blender: Thread [0] stopping.Thread [1] stopping.

V-Ray For Blender: Total sync time 35.362 sec.
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7E9AA8139
Module  : C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\blender.exe

I've zipped up the .vrscene files that were generated, in case they are useful. I'm not sure how to debug this further, or to provide more useful information.

Let me know if the vrscenes are helpful and I'll email you a link to the package.

**Comment by bdancer** [comment]
I'll need a blend-file not vrscenes.

**Comment by philstopford** [comment]
Working on it - trying to find the minimum case.... Bear with me.

**Comment by philstopford** [comment]
This seems to be intermittent, oddly. Trying again often causes the render to go through without any change. Not sure whether this makes it more or less interesting to you.

**Comment by philstopford** [comment]
Are there some additional debug flags I could try? This seems to be happening randomly across a number of scenes and I'm trying to understand what might be contributing.

**Comment by bdancer** [comment]
Blender has "-d" flag, not sure how useful it'll be.

**Comment by philstopford** [comment]
I sent a link to a Google drive folder for, admittedly large, content that triggers this. I hope this might be useful.

**Comment by philstopford** [comment]
Just following up on this again. If there's a preferred location other than Google Drive to submit content for cases like this, please let me know.

**Comment by bdancer** [comment]
@philstopford, we are looking into this issue, I can't say much right now.

**Comment by philstopford** [comment]
More power to your elbow - I hope you are able to resolve it. If you have the content, can I remove it from the Google Drive to save space?

Please do let me know if I can help in any way. I'm grateful for your support and hard work.

**Comment by bdancer** [comment]
@philstopford sure, I've downloaded the files.

**Comment by bdancer** [comment]
@philstopford should work fine in tomorrow nightly.

**Comment by philstopford** [comment]
Seems to be working, building from the current code. However, during render : 

ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!

Uncertain where that is coming from and how serious it might be.

**Comment by bdancer** [comment]
@philstopford those messages could appear, shouldn't do any harm just restart Blender.

**Comment by philstopford** [comment]
I can provoke a crash : 
1) Set up scene with distributed rendering, with two network nodes (I disabled rendering on the host - I only have two render licenses)
2) F12 a few frames to check all works.
3) Deselect one of the network nodes.
4) F12

Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF705003113
Module  : C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\blender.exe

The -d log shows this at the end:

eval fcurve 'pose.bones["hand.r"].constraints["rotFK"].influence' - 1.000000 => 1/3, 1
eval fcurve 'pose.bones["arm.l"].constraints["scaleIK"].influence' - 1.000000 => 1/3, 1
eval fcurve 'pose.bones["arm.l"].constraints["scaleFK"].influence' - 1.000000 => 1/3, 1
eval fcurve 'pose.bones["arm.r"].constraints["rotFK"].influence' - 1.000000 => 1/3, 1
eval fcurve 'pose.bones["arm.r"].constraints["scaleFK"].influence' - 1.000000 => 1/3, 1
eval fcurve 'pose.bones["arm.l"].constraints["rotFK"].influence' - 1.000000 => 1/3, 1
eval fcurve 'pose.bones["c_eyelid_base.l"].constraints["Copy Rotation"].influence' - 0.100000 => 1/2, 0
eval fcurve 'pose.bones["c_eyelid_base.r"].constraints["Copy Rotation"].influence' - 0.100000 => 1/2, 0
eval fcurve 'pose.bones["leg_i

**Comment by bdancer** [comment]
@philstopford weird...

**Comment by bdancer** [comment]
@philstopford there is a "lock" button at the right of the "Render" button - could you turn it on and check if this will help?

**Comment by philstopford** [comment]
That does seem to help. I've been playing with this on and off this morning. With the lock set, I got no crash. With the lock off, it crashed on F12. No idea what's the root cause, though.

**Comment by philstopford** [comment]
OK. I'm still getting a crash here if I render (F12) a few times (e.g. F12, wait, stop, F12, wait, stop, F12, wait, stop).

The crashlog still shows something like : 

eval fcurve 'pose.bones["arm.l"].constraints["rotFK"].influence' - 1.000000 => 1/3, 1
eval fcurve 'pose.bones["c_eyelid_base.l"].constraints["Copy Rotation"].influence' - 0.100000 => 1/2

This is all local rendering - no DR.

**Comment by bdancer** [comment]
I've changed export a bit, hope this'll help...

**Comment by philstopford** [comment]
It seems to be better, although I'm seeing Deadline requeuing jobs from exceptions thrown by blender.exe in conjunction with V-ray rendering. An example of the log output is below.

2018-10-31 07:38:07:  0: STDOUT: [2018/Oct/31|07:38:03]     Unknown property "metalness" in object "BRDFVRayMtl@NTpouldrons|L_____characters_xurge_srgr_Ranger_Armor_M3_nohelmet_noammo_simon_blend|L_____characters_xurge_characters_blend|L__pedestrians_blend|NStandard_Material"
2018-10-31 07:38:07:  0: STDOUT: [2018/Oct/31|07:38:03]     The adaptive option for the light cache is no longer supported and will be ignored.
2018-10-31 07:38:07:  0: STDOUT: V-Ray For Blender: vfb_free()
2018-10-31 07:38:09:  0: STDOUT: File "C:\Users\phil\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\bpainter_properties.py", line 387, in set_hotkeys
2018-10-31 07:38:09:  0: STDOUT: Error   : EXCEPTION_ACCESS_VIOLATION
2018-10-31 07:38:09:  0: STDOUT: Address : 0x00007FF603053EF3
2018-10-31 07:38:09:  0: STDOUT: Module  : C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\blender.exe
2018-10-31 07:38:09:  0: INFO: Process exit code: 11
2018-10-31 07:38:09:  0: Done executing plugin command of type 'Render Task'

=======================================================
Details
=======================================================
Date: 10/31/2018 07:39:02
Frames: 311-315
Elapsed Time: 00:05:35:59
Job Submit Date: 10/27/2018 15:39:29
Job User: phils
Average RAM Usage: 22644121600 (88%)
Peak RAM Usage: 25465253888 (99%)
Average CPU Usage: 80%
Peak CPU Usage: 100%
Used CPU Clocks (x10^6 cycles): 669023424
Total CPU Clocks (x10^6 cycles): 836279260

**Comment by bdancer** [comment]
So what should I do to recreate this issue? Setup Deadine with Blender? On that scene? What if you'll submit just the exported vrscene?

**Comment by philstopford** [comment]
The large scene I sent previously should reproduce this from what I can tell. All I did was set Deadline up to render (via blender) with two nodes and the failures show up in the log. It's not every task (of 5 frames) that causes a problem, and it generally seems to be happening at the end of the task, which causes Deadline to fail the entire task and re-queue it.

**Comment by bdancer** [comment]
@philstopford so it's happening only via Deadline?
What command line options Deadline supplies?
What if you run Blender with the same options locally? Will it crash?

**Comment by philstopford** [comment]
This is the full command:

"C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\blender.exe"  -b "D:\blender\SStation\nofusion_interiorWIP_r3.blend" -t 0 -s 375 -e 379 -a 

I'll try it here in a commandline, but it will take a few hours to see what happens

**Comment by philstopford** [comment]
Running that through the command line, I see the exact same fail, so it's unrelated to Deadline. It always seems to be associated with the vfb_free() in this case, after all of the rendering is done:

[2018/Oct/31|17:52:56]     The adaptive option for the light cache is no longer supported and will be ignored.
V-Ray For Blender: vfb_free()
Error: Not freed memory blocks: 138920, total unfreed memory 6.597916 MB
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF61D965783
Module  : C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\blender.exe

**Comment by bdancer** [comment]
@philstopford well, weird, but I can't make it crash...

**Comment by philstopford** [comment]
Any additional switches I can set to give more insight?

**Comment by bdancer** [comment]
@philstopford no idea sry, I need a way to make it crash here, otherwise I can't do much...

**Comment by philstopford** [comment]
Uploaded some smaller test content that is failing the same way for me at the end of each batch of 5 frames in a task (not just under Deadline Slave).. It's in the Google Drive and is showing as shared with you - let me know if that's not the case.

**Comment by bdancer** [comment]
@philstopford I've tried running it lots of time... no crash... very weird...

**Comment by philstopford** [comment]
Ahah. I've found the cause for the end of render task crash. Sending it to the right place. This can be closed.

**Comment by philstopford** [comment]
Actually, no, there's an interaction here specifically to V-ray and FlIP fluids addon.

If you have access to the FLIP fluids package, render with that addon. You'll get a crash. If you render with the non-Vray blender, there is no crash.

**Comment by philstopford** [comment]
Resolved with FLIP fluids change to their __init__.py file.
