### ISSUE TITLE
How to use the water / displacement

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#246]
Should this work on a basic plane mesh? I don't get any obvious displacement.

![water_node](https://user-images.githubusercontent.com/1983851/45983550-01bb9f00-c02b-11e8-9049-90ac15a82dd6.PNG)

**Comment by philstopford** [comment]
I've tried plugging the texture into the color and float inputs on the displacement node, without any obvious difference - I get a flat plane during render.

**Comment by bdancer** [comment]
Does this mesh contain UV?

**Comment by bdancer** [comment]
Also it'll be better to post such requests on forum since other users may help you.

**Comment by philstopford** [comment]
Posted here : https://forums.chaosgroup.com/forum/v-ray-for-blender-forums/v-ray-for-blender-tips-tricks-and-tutorials/1012269-how-to-use-water-texture

No answers up to now.

**Comment by philstopford** [comment]
Got an answer - it seems that this is done in a different node graph to the shader setup.
