### ISSUE TITLE
VrayToon Render Channel support

### ISSUE THREAD

**Issue by cyberlecs** [ChaosGroup/blender_with_vray_additions#247]
Hi,
Would be nice to have the VrayToon Render Channel option.
Different from VrayToon Render Effect (which burns the effect in the final image), this one creates a separate render pass with the edges.

https://docs.chaosgroup.com/display/VRAY3MAX/V-Ray+Toon+%7C+VRayToon

>  Parameters for plugin 'RenderChannelToon'
>   enableDeepOutput: bool = true
>   name: string = "ColorChannel"
>   alias: integer = 1000
>   color_mapping: bool = false, true to apply color mapping to the channel; false otherwise
>   consider_for_aa: bool = false
>   filtering: bool = true
>   derive_raw_channels: bool = true, true if raw channels should be derived from the respective color and filter channel
>   vfb_color_corrections: bool = true, False to disable ALL VFB color corrections(sRGB, curves, white balance, etc...) when saving the channel data to a file or showing it on a display. True to apply VFB color corrections when saving the channel data to a file or showing it on a display. If true some color corrections might still be disabled, based on the type of file being saved.
>   invert_color: bool = false
> Supported interfaces:
>         EXT_RENDER_CHANNEL

**Comment by poseidon4o** [comment]
@cyberlecs The render channel will be added with next nightly.

**Comment by cyberlecs** [comment]
Thanks!
