### ISSUE TITLE
AA Filter not working

### ISSUE THREAD

**Issue by cyberlecs** [ChaosGroup/blender_with_vray_additions#248]
Hi,
AA filter settings are not working anymore in recent builds. No matter what type of filter and size is used, the result is always the same as disabling AA filter (set to none).

Build version:
vrayblender35-2.79-a353eda-x86_64-windows
vraystd_adv_36004_x64_vc11_hwlic_utf8_28380

Sample scene with Adaptive DMC 1/24, Treshhold 0.01
Blend file: http://pasteall.org/blend/index.php?id=50412

![filter none](https://user-images.githubusercontent.com/338739/46133474-f88f2580-c216-11e8-95d0-7cf3fce0e750.jpg)
![filter gaussian](https://user-images.githubusercontent.com/338739/46133483-004eca00-c217-11e8-9c36-aa59ce62abf5.jpg)

**Comment by poseidon4o** [comment]
@cyberlecs This should be resolved with next nightly.

**Comment by cyberlecs** [comment]
Thanks! All fine now.
