### ISSUE TITLE
Support multiple search (or platform specific) paths for V-ray standalone?

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#255]
Using blender cloud to distribute prefs around between machines, including multiple platforms (Windows, macOS), would it be possible for the V-ray addon to support platform-specific path definitions to allow the user to point at V-ray standalone, and for the addon to use the correct path based on the platform being utilized?

For example, have 3 entries (one for each potential platform) that can be defined as 

Windows : C:\Program Files\Chaos Group\V-Ray\Standalone for x64\bin\x64\vc14\vray.exe
Linux : /usr/ChaosGroup/V-Ray/Standalone_for_linux_x64/bin/linux_x64/gcc-4.6/vray
macOS : /Applications/ChaosGroup/V-Ray/Standalone_for_mavericks_x64/bin/mavericks_x64/gcc-4.2/vray

**Comment by bdancer** [comment]
@philstopford if you have only one V-Ray installation on every platform then automatic detection should work fine. Have you tried "Detect V-Ray" option?

**Comment by philstopford** [comment]
That works, but I had to remove my V-ray/MODO install to get the detection to work (I installed V-ray standalone to avoid port-specific trouble)
