### ISSUE TITLE
Multiple objects with the same mesh data, only one is rendered

### ISSUE THREAD

**Issue by cyberlecs** [ChaosGroup/blender_with_vray_additions#256]
Hi @bdancer @poseidon4o 

In the recent build, sharing the same mesh data across multiple objects is not working anymore. Only the last one of them gets rendered.
It was working in the older version from 2018-10-26 (vrayblender35-2.79-9134bcc-x86_64-windows)

V-Ray 3.60.04
vrayblender35-2.79-1f36cd1-x86_64-windows
Sample File: http://pasteall.org/blend/index.php?id=50627

![screenshot](https://user-images.githubusercontent.com/338739/47918630-e0e93380-de8b-11e8-8b98-031a07a20779.jpg)

**Comment by bdancer** [comment]
Omg, fixing...

**Comment by bdancer** [comment]
Fixed with https://github.com/ChaosGroup/blender_with_vray_additions/commit/cdd2c77fac9a809c1f157351ff34a9912a686ad2.

**Comment by cyberlecs** [comment]
Wow...that was fast! xD
Thanks! 

Here is the theme: [cobalt_v4_theme.zip](https://github.com/ChaosGroup/blender_with_vray_additions/files/2543311/cobalt_v4_theme.zip)
I'm using Roboto Medium font from Google Web Fonts.
