### ISSUE TITLE
Fog Gizmo, fog node doesn't work.

### ISSUE THREAD

**Issue by kropaman** [ChaosGroup/blender_with_vray_additions#258]
Fog Gizmo doesn't work and some other volumetric nodes no errors objects just not rendered 

https://docs.chaosgroup.com/display/VFBlender/Fog+Gizmo

Trying to do similar https://forums.cgsociety.org/t/a-cube-rendered-as-volume-fog-smoke-vray/1613784

**Comment by poseidon4o** [comment]
@kropaman This should be resolved with 7d891b1
