### ISSUE TITLE
Issues with the package nodeitems_utils.py script

### ISSUE THREAD

**Issue by philstopford** [ChaosGroup/blender_with_vray_additions#260]
Trying to use SceneCity with this version of blender, I get errors in the console of the form : 

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\modules\nodeitems_utils.py", line 131, in draw_node_menu_item
    for i,item in enumerate(sorted(self.category.items(context), key=lambda t: getattr(bpy.types, t.nodetype).bl_rna.name)):
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\modules\nodeitems_utils.py", line 131, in <lambda>
    for i,item in enumerate(sorted(self.category.items(context), key=lambda t: getattr(bpy.types, t.nodetype).bl_rna.name)):
AttributeError: 'RNA_Types' object has no attribute 'StaticRoadPortionNode'

and none of the addons entries in its menus are available in the node editor. Nightly builds and 2.79b are fine, so this looks to be specific to the V-ray blender build corresponding to the https://github.com/ChaosGroup/blender_with_vray_additions/commit/5fdbde0235043e090cf032e5d7f0e4eaa4fc2d0e release

**Comment by philstopford** [comment]
It seems to be related to the icon code in this script. The attached works better.
[nodeitems_utils.py.txt](https://github.com/ChaosGroup/blender_with_vray_additions/files/2727852/nodeitems_utils.py.txt)

**Comment by philstopford** [comment]
This is still broken. Could you consider checking whether there's something funky in your branch?

**Comment by philstopford** [comment]
I felt the need to bump this.

**Comment by poseidon4o** [comment]
@philstopford How do you reproduce this? I can import .obj files without errors.

**Comment by philstopford** [comment]
This does seem to be working in 706cd8b. It wasn't working for me in 999e565 or earlier.

**Comment by philstopford** [comment]
Actually, the OBJ comments should go to https://github.com/ChaosGroup/blender_with_vray_additions/issues/261

The problem with the nodeitems_utils.py script remains - SceneCity is broken with blender/V-ray port.

**Comment by philstopford** [comment]
To recap the changes in this patched script, which I tested with the 706cd8b install : 

    def draw_node_menu_item(self, context):
        layout = self.layout.row()
        col = layout.column()
        for item in self.category.items(context):
            item.draw(item, col, context)
        # Original block below simply doesn't work with SceneCity
        '''
        for i,item in enumerate(sorted(self.category.items(context), key=lambda t: getattr(bpy.types, t.nodetype).bl_rna.name)):
            if self.category.split_items is not None:
                if i and i % self.category.split_items == 0:
                    col = layout.column()
            item.draw(item, col, context)
        '''

and then there is a built-in assumption that icons exist in the item draw code, which seems to react better with a try/except : 

    def draw(self, layout, context):
        default_context = bpy.app.translations.contexts.default
        try:
            props = layout.operator("node.add_node", text=self.label, text_ctxt=default_context, icon=self.icon)
        except:
            props = layout.operator("node.add_node", text=self.label, text_ctxt=default_context)

**Comment by philstopford** [comment]
Just  following up on this : https://github.com/ChaosGroup/blender_with_vray_additions/commit/2901eb73122eaf8fe28c4f6e3415666ac9e2ed49 still has the problem

**Comment by philstopford** [comment]
Bumping again. Has activity ceased for the time being?

**Comment by poseidon4o** [comment]
@philstopford Unfortunatelly SceneCity is paid and I can't test if the changes will fix it really. Anyway I added them with 9edd2f87fa5e2e000a5ca4f241b034f69214add8 test and write back when you can.

**Comment by philstopford** [comment]
I'll try and build from source later this week; it looks like there are no automated builds currently being generated by ChaosGroup. I'll let you know how I get on.

**Comment by poseidon4o** [comment]
Builds are running now, they should appear soon in the nightlies.

**Comment by philstopford** [comment]
Looks good here - thanks. Build service saved me the trouble :)
