### ISSUE TITLE
If I remove is_prepass from this line I get fog object gizmo to work again.

### ISSUE THREAD

**Issue by haikalle** [ChaosGroup/blender_with_vray_additions#263]
https://github.com/ChaosGroup/blender_with_vray_additions/blob/1b210468d9bee5a3d929d64a736dd7cd949bcb6e/intern/vray_for_blender_rt/src/plugin_exporter/vfb_plugin_exporter.cpp#L65

**Comment by poseidon4o** [comment]
Fog Gizmo should be working fine with 7d891b1
